name: Robot tests

on:
  workflow_dispatch:
  push:
    branches:
      - "tech-support-python"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Run linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: install containerlab
        run: bash -c "$(curl -sL https://get.containerlab.dev)"
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./support/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - name: Run automated tests
        run: make automation-test

      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test results
          path: |
            tests/log.html
            tests/report.html
            tests/output.xml

  build-rpm-package:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./support/.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
      - name: Build RPM package
        run: make build-app
      - name: upload RPM package
        uses: actions/upload-artifact@v3
        with:
          name: RPM package
          path: build/support-*.rpm
      # Publish RPM package to Repo??
