name: Robot tests

on:
  workflow_dispatch:
  push:
    branches:
      - "tech-support-python"

jobs:
  install-containerlab:
    runs-on: ubuntu-latest
    steps:
      - name: install containerlab
        run: bash -c "$(curl -sL https://get.containerlab.dev)"

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

  lint:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: ls
        run: ls
      - name: Run linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs: [install-containerlab, checkout]
    steps:
      - name: Run automated tests
        run: make automation-test

  upload-artifact:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test results
          path: |
            tests/log.html
            tests/report.html
            tests/output.xml
